spring:
  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-prod1.yml
      - classpath:/yml/application-prod2.yml
      - classpath:/yml/application-gpt.yml
  profiles:
    group:
      prod1: prod1, gpt
      prod2: prod2, gpt
      local: local, gpt
    active: prod2