spring:
  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-prod1.yml
      - classpath:/yml/application-prod2.yml
  profiles:
    group:
      prod1: prod1
      prod2: prod2
      local: local
    active: prod2