# 워크플로우의 이름 지정
name: Memorlink CD

on:
  push:
    branches: [ main ]

env:
  S3_BUCKET_NAME: memorlink-sever        # <- 실제 버킷명 (sever)
  S3_KEY: memorlink_server.zip           # 업로드/배포 공통 zip 파일명

jobs:
  build:
    name: Code deployment
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    # 환경변수 파일 생성
    - name: Generate application.yml
      shell: bash
      run: |
        mkdir -p ./src/main/resources
        printf '%s' "${{ secrets.SOPT_APPLICATION }}" > ./src/main/resources/application.yml

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Make Directory
      run: mkdir -p deploy

    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    # appspec.yml 안전 복사 (없으면 스킵)
    - name: Copy appspec.yml (optional)
      shell: bash
      run: |
        if [ -f appspec.yml ]; then
          cp appspec.yml ./deploy
          echo "✔ appspec.yml copied."
        else
          echo "⚠ appspec.yml not found, skipping copy."
        fi

    # scripts/*.sh 안전 복사 (없으면 스킵)
    - name: Copy script files (optional)
      shell: bash
      run: |
        if ls ./scripts/*.sh >/dev/null 2>&1; then
          cp ./scripts/*.sh ./deploy
          echo "✔ scripts copied."
        else
          echo "⚠ No scripts/*.sh found, skipping copy."
        fi

    - name: Make zip file
      shell: bash
      run: zip -r "./${{ env.S3_KEY }}" ./deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp "./${{ env.S3_KEY }}" "s3://$S3_BUCKET_NAME/$S3_KEY" --region ap-northeast-2

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      shell: bash
      run: |
        aws deploy create-deployment \
          --application-name sopt-server-codedeploy \
          --deployment-group-name sopt-server-codedeploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$S3_KEY \
          --region ap-northeast-2
